# Generated by Django 3.1.5 on 2021-01-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetime',
            name='day',
        ),
        migrations.AlterField(
            model_name='freetime',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='freetime',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
