# Generated by Django 3.1.5 on 2021-01-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210121_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='google_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
