# Generated by Django 3.1.5 on 2021-01-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slots',
            field=models.IntegerField(default=1),
        ),
    ]
