# Generated by Django 3.1.5 on 2021-01-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='topic',
        ),
    ]
